# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

# Trigger Keypoint
on:
  push:
    tags: 
      - 'v*.*'    # 匹配 v1.0, v1.1 等兩段的標籤
      - 'v*.*.*'  # 匹配 v1.0.0, v2.1.5 等三段的標籤
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout codes
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

     # By Manual 
     # 1.Check if you have gpg keys
     # 2.Save credential at gradle.properties
     # 3.Set `myLibrary` as new child of publication
     
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew build

    
    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to GitHub Packages
      run: ./gradlew publishMyLibraryPublicationToMavenRepository --no-configuration-cache -scan
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GPR_TOKEN }}
